ALTER TYPE "StrategyActionType" ADD VALUE IF NOT EXISTS 'RECOVERY_DCA_ENTRY';

ALTER TABLE "TradingStrategy"
  ADD COLUMN IF NOT EXISTS "recoveryEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "recoveryMaxOrders" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "recoveryStepPercents" JSONB NOT NULL DEFAULT '[5,8,12,18,25]'::jsonb,
  ADD COLUMN IF NOT EXISTS "recoveryMultipliers" JSONB NOT NULL DEFAULT '[1,1.5,2,3,5]'::jsonb,
  ADD COLUMN IF NOT EXISTS "recoveryTakeProfitPercent" DECIMAL(10,4) NOT NULL DEFAULT 1.5;

ALTER TABLE "TradingPosition"
  ADD COLUMN IF NOT EXISTS "recoveryMode" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "recoveryDcaCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "recoveryAnchorPrice" DECIMAL(28,12),
  ADD COLUMN IF NOT EXISTS "recoveryTakeProfitPrice" DECIMAL(28,12);
